import { dirname, join } from "node:path"
import type { StateResource } from "@monolith/core"
import type { WranglerImportResult } from "./wrangler-import.js"

export const MONOLITH_ENV_FILENAME = "monolith.env.d.ts"

const KIND_TO_TS: Record<string, string> = {
  d1: "D1Database",
  kv: "KVNamespace",
  r2: "R2Bucket",
  queue: "Queue"
}

export interface BindingTypeEntry {
  binding: string
  tsType: string
}

export function envTypesRelativePath(mainEntry: string): string {
  const dir = dirname(mainEntry)
  return dir === "." ? MONOLITH_ENV_FILENAME : join(dir, MONOLITH_ENV_FILENAME)
}

export function bindingEntriesFromImportResult(result: WranglerImportResult): BindingTypeEntry[] {
  const entries: BindingTypeEntry[] = []

  for (const entry of result.d1Databases) {
    entries.push({ binding: entry.binding, tsType: "D1Database" })
  }

  for (const entry of result.kvNamespaces) {
    entries.push({ binding: entry.binding, tsType: "KVNamespace" })
  }

  for (const entry of result.r2Buckets) {
    entries.push({ binding: entry.binding, tsType: "R2Bucket" })
  }

  for (const entry of result.queues) {
    entries.push({ binding: entry.binding, tsType: "Queue" })
  }

  return entries
}

export function bindingEntriesFromStateResources(resources: StateResource[]): BindingTypeEntry[] {
  return resources.flatMap((resource) => {
    if (!resource.binding) {
      return []
    }

    const tsType = KIND_TO_TS[resource.kind]
    if (!tsType) {
      return []
    }

    return [{ binding: resource.binding, tsType }]
  })
}

export function generateMonolithEnvDts(entries: BindingTypeEntry[]): string {
  const lines = [
    "// auto-generated by monolith — do not edit",
    "",
    "export interface MonolithEnv {"
  ]

  if (entries.length === 0) {
    lines.push("  // no bindings")
  } else {
    for (const entry of entries) {
      lines.push(`  ${entry.binding}: ${entry.tsType}`)
    }
  }

  lines.push("}")
  lines.push("")
  return lines.join("\n")
}
