import { describe, expect, it } from "vitest"
import {
  bindingEntriesFromImportResult,
  bindingEntriesFromStateResources,
  envTypesRelativePath,
  generateMonolithEnvDts
} from "./typegen.js"
import { parseWranglerConfigText } from "./wrangler-import.js"

const dogfoodConfig = `
{
  "name": "monolith-m1-dogfood",
  "main": "src/index.ts",
  "d1_databases": [{ "binding": "DB", "database_name": "dogfood-db", "database_id": "abc" }],
  "kv_namespaces": [{ "binding": "KV", "id": "def" }]
}
`

describe("typegen", () => {
  it("maps import bindings to TypeScript env entries", () => {
    const result = parseWranglerConfigText(dogfoodConfig, "wrangler.jsonc")
    expect(bindingEntriesFromImportResult(result)).toEqual([
      { binding: "DB", tsType: "D1Database" },
      { binding: "KV", tsType: "KVNamespace" }
    ])
  })

  it("maps state resources to TypeScript env entries", () => {
    expect(
      bindingEntriesFromStateResources([
        { id: "worker:app", kind: "worker", name: "app" },
        { id: "d1:DB", kind: "d1", binding: "DB", databaseId: "abc" },
        { id: "kv:KV", kind: "kv", binding: "KV", namespaceId: "def" }
      ])
    ).toEqual([
      { binding: "DB", tsType: "D1Database" },
      { binding: "KV", tsType: "KVNamespace" }
    ])
  })

  it("places env types beside the worker main entry", () => {
    expect(envTypesRelativePath("src/index.ts")).toBe("src/monolith.env.d.ts")
    expect(envTypesRelativePath("index.ts")).toBe("monolith.env.d.ts")
  })

  it("generates MonolithEnv interface d.ts content", () => {
    const output = generateMonolithEnvDts([
      { binding: "DB", tsType: "D1Database" },
      { binding: "KV", tsType: "KVNamespace" }
    ])

    expect(output).toContain("// auto-generated by monolith")
    expect(output).toContain("export interface MonolithEnv {")
    expect(output).toContain("  DB: D1Database")
    expect(output).toContain("  KV: KVNamespace")
  })
})
